name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: sudo apt update && sudo apt install gem ruby -y --no-install-recommends && sudo gem install fpm
      
    - name: Install dependencies
      run: make
      
    - name: Make Deb
      run: make deb
      
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Deb Package
        Path: battery-guard*.deb
        retention-days: 5
