name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: apt update && apt install gem ruby -y --no-install-recommends && gem install fpm
      
    - name: Install dependencies
      run: make
      
    - name: Make Deb
      run: make deb
      
